# Generated by Django 6.0.7 on 2026-07-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderAdyenConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adyen_merchant_account', models.CharField(max_length=255)),
                ('adyen_api_key', models.CharField(max_length=255)),
                ('adyen_client_key', models.CharField(max_length=255)),
                ('adyen_hmac_key', models.CharField(max_length=255)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adyen_config', to='payments_core.paymentprovider')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTokenAdyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurring_detail_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('adyen_shopper_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adyen_details', to='payments_core.paymenttoken')),
            ],
        ),
    ]
