# Generated by Django 6.0.7 on 2026-07-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_adyen', '0002_alter_paymentprovideradyenconfig_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentprovideradyenconfig',
            name='adyen_theme_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
