# Generated by Django 6.0.7 on 2026-07-26 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderStripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_publishable_key', models.CharField(max_length=255)),
                ('stripe_secret_key', models.CharField(max_length=255)),
                ('stripe_webhook_secret', models.CharField(max_length=255)),
                ('provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_config', to='payments_core.paymentprovider')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTokenStripe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_mandate', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_details', to='payments_core.paymenttoken')),
            ],
        ),
    ]
