# Generated by Django 6.0.7 on 2026-07-26 15:49
#
# AlterModelTable is a safe, in-place rename: Django turns each of these
# into a plain `ALTER TABLE ... RENAME TO ...` on Postgres, which just
# relabels the existing table (and all its rows) - no drop, no recreate, no
# data loss. Contrast this with the earlier admin/auth/sessions cleanup,
# where we recommended dropping and recreating the whole database instead:
# that was because REMOVING an app entirely leaves Django with no model to
# generate a migration FROM in the first place, so there's nothing to
# migrate - only reset. Here we're just renaming a table for a model that
# still exists, which is exactly what makemigrations/migrate are built to
# do safely.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_stripe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentproviderstripeconfig',
            table='payment_provider_stripe_config',
        ),
        migrations.AlterModelTable(
            name='paymenttokenstripe',
            table='payment_token_stripe',
        ),
    ]
