# Generated by Django 6.0.7 on 2026-07-26 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('disabled', 'Disabled'), ('test', 'Test Mode'), ('enabled', 'Enabled')], default='disabled', max_length=16)),
                ('support_manual_capture', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('none', 'None'), ('partial', 'Partial'), ('full', 'Full')], default='not_implemented', max_length=16)),
                ('support_refund', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('none', 'None'), ('partial', 'Partial'), ('full', 'Full')], default='not_implemented', max_length=16)),
                ('support_tokenization', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('none', 'None'), ('partial', 'Partial'), ('full', 'Full')], default='not_implemented', max_length=16)),
                ('support_express_checkout', models.CharField(choices=[('not_implemented', 'Not Implemented'), ('none', 'None'), ('partial', 'Partial'), ('full', 'Full')], default='not_implemented', max_length=16)),
                ('allow_tokenization', models.BooleanField(default=False)),
                ('capture_manually', models.BooleanField(default=False)),
                ('allow_express_checkout', models.BooleanField(default=False)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_providers', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PaymentToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_details', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tokens', to='tenants.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='payments_core.paymentprovider')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_tokens', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=255)),
                ('provider_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('captured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('done', 'Done'), ('cancel', 'Cancelled'), ('error', 'Error')], default='draft', max_length=16)),
                ('state_message', models.TextField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('online_redirect', 'Online Redirect'), ('online_direct', 'Online Direct'), ('online_token', 'Online Token'), ('refund', 'Refund')], default='online_redirect', max_length=32)),
                ('last_state_change', models.DateTimeField(blank=True, null=True)),
                ('tokenize', models.BooleanField(default=False)),
                ('is_express_checkout', models.BooleanField(default=False)),
                ('return_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_post_processed', models.BooleanField(default=False)),
                ('provider_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.customer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments_core.paymentprovider')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_transactions', to='payments_core.paymenttransaction')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tenants.tenant')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments_core.paymenttoken')),
            ],
            options={
                'unique_together': {('tenant', 'reference')},
            },
        ),
    ]
