# Generated by Django 6.0.7 on 2026-07-26 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttoken',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='payments_core.paymentprovider'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments_core.paymentprovider'),
        ),
    ]
