# Generated by Django 6.0.7 on 2026-07-26 15:49
#
# AlterModelTable is a safe, in-place rename: Django turns each of these
# into a plain `ALTER TABLE ... RENAME TO ...` on Postgres, which just
# relabels the existing table (and all its rows) - no drop, no recreate, no
# data loss. Contrast this with the earlier admin/auth/sessions cleanup,
# where we recommended dropping and recreating the whole database instead:
# that was because REMOVING an app entirely leaves Django with no model to
# generate a migration FROM in the first place, so there's nothing to
# migrate - only reset. Here we're just renaming a table for a model that
# still exists, which is exactly what makemigrations/migrate are built to
# do safely.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_core', '0002_alter_paymenttoken_provider_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentprovider',
            table='payment_provider',
        ),
        migrations.AlterModelTable(
            name='paymenttoken',
            table='payment_token',
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transaction',
        ),
    ]
